### ISSUE TITLE
YouTube の登録者数をスキーマに含めるべきか

### ISSUE THREAD

**Issue by saitoeku3** [vtuber-lod/vtuber-lod#4]
VTuber の人気度などの指標として YouTube の登録者数を用いることが多いため、
スキーマに含まれているとユーザーにとってより親切な LOD になると思います。

しかし、毎日大きく変化しているデータであるため更新や管理が複雑になりそうなので、
「含めるならどのような手法を用いるのか」「そもそも含めないのか」について議論したいです。

**Comment by takanakahiko** [comment]
基本的にLODは動的なデータに向いていません。
LODの本質はデータをつなげることにあると個人的には考えます。
そこで、なるべく自分でホストしなくていいデータは外部に任せるのです。
Web上に重複するデータをムリに増やす必要は無いのです。
そこで、登録者数なんかはLODに必須ではないと思います。

例えば「キズナアイ」の登録者数を調べる時にLODの役割としては「キズナアイという名前とチャンネルIDを紐付ける」ことが最低限の役割だと思います。APIを叩くための橋渡しをすることに徹するほうが良いと思います。

一方、LODが登録者数を提供する意義も理解しました。仕組みさえ整えば導入しても良いですが、中途半端になったりするのであれば、他の開発リソースへ割くのが良いのかなといった見解です。

**Comment by saitoeku3** [comment]
> LODの本質はデータをつなげることにある

この考えに納得できました。
確かに最初はデータをつなげるために最低限必要なことから取り組むべきなので、この話は先送り (もしくは含まない) にして良いと思います。

まずはチャンネル ID や URL を含められれば十分ですね。

**Comment by takanakahiko** [comment]
押し付けのようになってしまい、すみません。
ご提案感謝します！

一度これは閉じて、必要な時に再度議論しましょう

**Comment by nekketsuuu** [comment]
現在の YouTube チャンネル登録者数は API 越しに分かりますが過去のデータは分からないので、変遷を見たくなった場合は適宜取得してタイムスタンプと一緒に保存していくのはアリだと思います。[SocialBlade](https://socialblade.com/) の表やグラフみたいなのを描画したくなった場合を考えています。

ただ全 VTuber のチャンネル登録者数を毎日真面目に集計すると YouTube API をたくさん叩きそうなのでお金は必要でしょうが……。
